### ISSUE TITLE
Game Over: False

### ISSUE THREAD

**Issue by rwforest** [clarkerubber/Python-Puzzle-Creator#8]
I modified the code to read from a pgn file. I iterated it till the end and made sure that it is_game_over(). But I am unable to generate any puzzle.

It always gave me this error:

Not Going Deeper:
   Ambiguous: True
   Game Over: False
   Has Best Move: True
Puzzle incomplete

[game.txt](https://github.com/clarkerubber/Python-Puzzle-Creator/files/526705/game.txt)

**Comment by rwforest** [comment]
@clarkerubber so I ran a bunch of PGN by Magnus Carlsen, the job kicked off after a few hours, only 2 got generated successfully. Is the rule being too strict to select good moves?

**Comment by clarkerubber** [comment]
Nope. It just doesn't allow for ambiguous puzzles. If there's more than 1 good move, it's not a good puzzle and should be rejected. This is why at lichess we have a fleet of servers scanning games and generating puzzles because the chance of getting a puzzle from a game is quite low.

**Comment by rwforest** [comment]
so if you can't get a puzzle from a game, then what is the point of the
generator? Even parsing games from world champs cannot get good moves? Then
what kind of game can get good moves?

**Comment by clarkerubber** [comment]
https://en.lichess.org/training/>any number between 60k and 100k< will answer your question. There's lots of puzzles that link to games which are good for puzzles.
